pipeline {
    agent any  // Use any available agent

    stages {
        stage('Build') {
            steps {
                echo 'Building vote application...'
                dir('vote') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests on vote application...'
                dir('vote') {
                    sh 'pytest'
                }
            }
        }

        stage('Docker Build & Push') {
            environment {
                DOCKER_HUB_CREDENTIALS = credentials('dockerlogin')  // Ensure you have this credential set in Jenkins
            }
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_HUB_CREDENTIALS) {
                        def voteImage = docker.build("chrisanich/vote:${env.BUILD_NUMBER}", "./vote")
                        voteImage.push()
                        voteImage.push('latest')
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Build and Docker packaging for vote application is complete.'
        }
    }
}
